// Code generated by protoc-gen-go. DO NOT EDIT.
// source: highscore.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetHighScoreRequest struct {
	HighScore            float64  `protobuf:"fixed64,1,opt,name=high_score,json=highScore,proto3" json:"high_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHighScoreRequest) Reset()         { *m = SetHighScoreRequest{} }
func (m *SetHighScoreRequest) String() string { return proto.CompactTextString(m) }
func (*SetHighScoreRequest) ProtoMessage()    {}
func (*SetHighScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1bfe52306d72d22, []int{0}
}

func (m *SetHighScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHighScoreRequest.Unmarshal(m, b)
}
func (m *SetHighScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHighScoreRequest.Marshal(b, m, deterministic)
}
func (m *SetHighScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHighScoreRequest.Merge(m, src)
}
func (m *SetHighScoreRequest) XXX_Size() int {
	return xxx_messageInfo_SetHighScoreRequest.Size(m)
}
func (m *SetHighScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHighScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetHighScoreRequest proto.InternalMessageInfo

func (m *SetHighScoreRequest) GetHighScore() float64 {
	if m != nil {
		return m.HighScore
	}
	return 0
}

type SetHighScoreResponse struct {
	Set                  bool     `protobuf:"varint,1,opt,name=set,proto3" json:"set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHighScoreResponse) Reset()         { *m = SetHighScoreResponse{} }
func (m *SetHighScoreResponse) String() string { return proto.CompactTextString(m) }
func (*SetHighScoreResponse) ProtoMessage()    {}
func (*SetHighScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1bfe52306d72d22, []int{1}
}

func (m *SetHighScoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHighScoreResponse.Unmarshal(m, b)
}
func (m *SetHighScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHighScoreResponse.Marshal(b, m, deterministic)
}
func (m *SetHighScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHighScoreResponse.Merge(m, src)
}
func (m *SetHighScoreResponse) XXX_Size() int {
	return xxx_messageInfo_SetHighScoreResponse.Size(m)
}
func (m *SetHighScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHighScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetHighScoreResponse proto.InternalMessageInfo

func (m *SetHighScoreResponse) GetSet() bool {
	if m != nil {
		return m.Set
	}
	return false
}

type GetHighScoreRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHighScoreRequest) Reset()         { *m = GetHighScoreRequest{} }
func (m *GetHighScoreRequest) String() string { return proto.CompactTextString(m) }
func (*GetHighScoreRequest) ProtoMessage()    {}
func (*GetHighScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1bfe52306d72d22, []int{2}
}

func (m *GetHighScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHighScoreRequest.Unmarshal(m, b)
}
func (m *GetHighScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHighScoreRequest.Marshal(b, m, deterministic)
}
func (m *GetHighScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHighScoreRequest.Merge(m, src)
}
func (m *GetHighScoreRequest) XXX_Size() int {
	return xxx_messageInfo_GetHighScoreRequest.Size(m)
}
func (m *GetHighScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHighScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHighScoreRequest proto.InternalMessageInfo

type GetHighScoreRespone struct {
	HighScore            float64  `protobuf:"fixed64,1,opt,name=high_score,json=highScore,proto3" json:"high_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHighScoreRespone) Reset()         { *m = GetHighScoreRespone{} }
func (m *GetHighScoreRespone) String() string { return proto.CompactTextString(m) }
func (*GetHighScoreRespone) ProtoMessage()    {}
func (*GetHighScoreRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1bfe52306d72d22, []int{3}
}

func (m *GetHighScoreRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHighScoreRespone.Unmarshal(m, b)
}
func (m *GetHighScoreRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHighScoreRespone.Marshal(b, m, deterministic)
}
func (m *GetHighScoreRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHighScoreRespone.Merge(m, src)
}
func (m *GetHighScoreRespone) XXX_Size() int {
	return xxx_messageInfo_GetHighScoreRespone.Size(m)
}
func (m *GetHighScoreRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHighScoreRespone.DiscardUnknown(m)
}

var xxx_messageInfo_GetHighScoreRespone proto.InternalMessageInfo

func (m *GetHighScoreRespone) GetHighScore() float64 {
	if m != nil {
		return m.HighScore
	}
	return 0
}

func init() {
	proto.RegisterType((*SetHighScoreRequest)(nil), "m.highscore.v1.SetHighScoreRequest")
	proto.RegisterType((*SetHighScoreResponse)(nil), "m.highscore.v1.SetHighScoreResponse")
	proto.RegisterType((*GetHighScoreRequest)(nil), "m.highscore.v1.GetHighScoreRequest")
	proto.RegisterType((*GetHighScoreRespone)(nil), "m.highscore.v1.GetHighScoreRespone")
}

func init() { proto.RegisterFile("highscore.proto", fileDescriptor_a1bfe52306d72d22) }

var fileDescriptor_a1bfe52306d72d22 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xc8, 0x4c, 0xcf,
	0x28, 0x4e, 0xce, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcb, 0xd5, 0x43,
	0x08, 0x95, 0x19, 0x2a, 0x99, 0x70, 0x09, 0x07, 0xa7, 0x96, 0x78, 0x64, 0xa6, 0x67, 0x04, 0x83,
	0x84, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb9, 0xb8, 0x40, 0xca, 0xe2, 0xc1,
	0xea, 0x24, 0x18, 0x15, 0x18, 0x35, 0x18, 0x83, 0x38, 0x33, 0x60, 0xaa, 0x94, 0x34, 0xb8, 0x44,
	0x50, 0x75, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x09, 0x70, 0x31, 0x17, 0xa7, 0x96, 0x80,
	0xd5, 0x73, 0x04, 0x81, 0x98, 0x4a, 0xa2, 0x5c, 0xc2, 0xee, 0x98, 0xe6, 0x83, 0xac, 0x75, 0xc7,
	0x30, 0x20, 0x95, 0x80, 0xb5, 0x46, 0xbb, 0x19, 0xb9, 0x58, 0xdc, 0x13, 0x73, 0x53, 0x85, 0x22,
	0xb9, 0x78, 0x90, 0xed, 0x17, 0x52, 0xd6, 0x43, 0xf5, 0x96, 0x1e, 0x16, 0x3f, 0x49, 0xa9, 0xe0,
	0x57, 0x04, 0xf5, 0x42, 0x04, 0x17, 0x8f, 0x3b, 0x5e, 0xa3, 0xb1, 0x78, 0x47, 0x8a, 0x80, 0x22,
	0xb0, 0xe7, 0x9c, 0xd8, 0xa2, 0x58, 0xd2, 0x13, 0x73, 0x53, 0x93, 0xd8, 0xc0, 0x31, 0x61, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x63, 0x5c, 0x48, 0xb6, 0x9c, 0x01, 0x00, 0x00,
}
